export const departments = [
  { id: 'd1', name: 'Engineering' },
  { id: 'd2', name: 'Marketing' },
  { id: 'd3', name: 'Design' },
  { id: 'd4', name: 'Sales' },
];

export const users = [
  { id: 'u1', name: 'Alex Morgan', role: 'admin', departmentId: 'd1', avatar: 'https://i.pravatar.cc/150?u=u1' },
  { id: 'u2', name: 'Sam Kerr', role: 'employee', departmentId: 'd1', avatar: 'https://i.pravatar.cc/150?u=u2' },
  { id: 'u3', name: 'Megan Rapinoe', role: 'employee', departmentId: 'd1', avatar: 'https://i.pravatar.cc/150?u=u3' },
  { id: 'u4', name: 'Trinity Rodman', role: 'employee', departmentId: 'd2', avatar: 'https://i.pravatar.cc/150?u=u4' },
  { id: 'u5', name: 'Sophia Smith', role: 'employee', departmentId: 'd3', avatar: 'https://i.pravatar.cc/150?u=u5' },
  { id: 'u6', name: 'Rose Lavelle', role: 'employee', departmentId: 'd4', avatar: 'https://i.pravatar.cc/150?u=u6' },
  { id: 'u7', name: 'Meghna', role: 'employee', departmentId: 'd1', avatar: 'https://i.pravatar.cc/150?u=u7' },
];

export const ticketStatuses = [
  { id: 'open', name: 'Open', color: 'bg-blue-500/20 text-blue-300 border-blue-500/30' },
  { id: 'in-progress', name: 'In Progress', color: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30' },
  { id: 'review', name: 'Under Review', color: 'bg-purple-500/20 text-purple-300 border-purple-500/30' },
  { id: 'resolved', name: 'Resolved', color: 'bg-green-500/20 text-green-300 border-green-500/30' },
  { id: 'closed', name: 'Closed', color: 'bg-gray-500/20 text-gray-300 border-gray-500/30' },
];

export const initialTickets = [
  {
    id: 't1',
    ticketNumber: 'TKT-001',
    title: 'Develop new landing page',
    description: 'Create a responsive and animated landing page for the new campaign.',
    priority: 'high',
    status: 'open',
    category: 'development',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString().split('T')[0],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    assignedTo: ['u2', 'u3'],
    createdBy: 'u1',
    departmentId: 'd1',
    comments: [
      {
        id: 'c1',
        userId: 'u1',
        content: 'Please ensure the landing page is mobile-responsive and follows our brand guidelines.',
        createdAt: new Date().toISOString(),
      }
    ],
  },
  {
    id: 't2',
    ticketNumber: 'TKT-002',
    title: 'Design marketing assets',
    description: 'Create banners and social media posts for the upcoming product launch.',
    priority: 'medium',
    status: 'in-progress',
    category: 'design',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString().split('T')[0],
    createdAt: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    updatedAt: new Date().toISOString(),
    assignedTo: ['u5'],
    createdBy: 'u1',
    departmentId: 'd3',
    comments: [
      {
        id: 'c2',
        userId: 'u1',
        content: 'Started working on the banner designs. Will have initial drafts ready by tomorrow.',
        createdAt: new Date(new Date().setHours(new Date().getHours() - 2)).toISOString(),
      },
      {
        id: 'c3',
        userId: 'u5',
        content: 'Great! Looking forward to seeing the designs.',
        createdAt: new Date(new Date().setHours(new Date().getHours() - 1)).toISOString(),
      }
    ],
  },
  {
    id: 't3',
    ticketNumber: 'TKT-003',
    title: 'Prepare sales pitch deck',
    description: 'Finalize the Q3 sales presentation with updated metrics and projections.',
    priority: 'high',
    status: 'resolved',
    category: 'sales',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString().split('T')[0],
    createdAt: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    updatedAt: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    assignedTo: ['u6'],
    createdBy: 'u1',
    departmentId: 'd4',
    comments: [
      {
        id: 'c4',
        userId: 'u6',
        content: 'Presentation is complete and ready for review.',
        createdAt: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
      }
    ],
  },
  {
    id: 't4',
    ticketNumber: 'TKT-004',
    title: 'Marketing campaign analysis',
    description: 'Analyze the performance of our recent marketing campaigns and provide insights.',
    priority: 'medium',
    status: 'open',
    category: 'analysis',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString().split('T')[0],
    createdAt: new Date(new Date().setHours(new Date().getHours() - 3)).toISOString(),
    updatedAt: new Date(new Date().setHours(new Date().getHours() - 3)).toISOString(),
    assignedTo: ['u4'],
    createdBy: 'u1',
    departmentId: 'd2',
    comments: [],
  },
  {
    id: 't5',
    ticketNumber: 'TKT-005',
    title: 'Database optimization task',
    description: 'Optimize database queries for better performance and faster response times.',
    priority: 'high',
    status: 'open',
    category: 'development',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString().split('T')[0],
    createdAt: new Date(new Date().setHours(new Date().getHours() - 1)).toISOString(),
    updatedAt: new Date(new Date().setHours(new Date().getHours() - 1)).toISOString(),
    assignedTo: ['u7'],
    createdBy: 'u1',
    departmentId: 'd1',
    comments: [],
  },
  {
    id: 't6',
    ticketNumber: 'TKT-006',
    title: 'API integration project',
    description: 'Integrate third-party payment gateway API with our existing system.',
    priority: 'medium',
    status: 'in-progress',
    category: 'development',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 8)).toISOString().split('T')[0],
    createdAt: new Date(new Date().setHours(new Date().getHours() - 2)).toISOString(),
    updatedAt: new Date().toISOString(),
    assignedTo: ['u7'],
    createdBy: 'u1',
    departmentId: 'd1',
    comments: [
      {
        id: 'c5',
        userId: 'u1',
        content: 'Please coordinate with the payment team for API documentation.',
        createdAt: new Date(new Date().setHours(new Date().getHours() - 1)).toISOString(),
      }
    ],
  },
];

export const initialNotifications = [
  {
    id: 'n1',
    userId: 'u2',
    type: 'ticket_assigned',
    title: 'New Ticket Assigned',
    message: 'You have been assigned ticket TKT-001: Develop new landing page',
    ticketId: 't1',
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n2',
    userId: 'u3',
    type: 'ticket_assigned',
    title: 'New Ticket Assigned',
    message: 'You have been assigned ticket TKT-001: Develop new landing page',
    ticketId: 't1',
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'n3',
    userId: 'u5',
    type: 'ticket_assigned',
    title: 'New Ticket Assigned',
    message: 'You have been assigned ticket TKT-002: Design marketing assets',
    ticketId: 't2',
    read: false,
    createdAt: new Date(new Date().setHours(new Date().getHours() - 1)).toISOString(),
  },
  {
    id: 'n4',
    userId: 'u6',
    type: 'ticket_assigned',
    title: 'New Ticket Assigned',
    message: 'You have been assigned ticket TKT-003: Prepare sales pitch deck',
    ticketId: 't3',
    read: false,
    createdAt: new Date(new Date().setHours(new Date().getHours() - 2)).toISOString(),
  },
  {
    id: 'n5',
    userId: 'u4',
    type: 'ticket_assigned',
    title: 'New Ticket Assigned',
    message: 'You have been assigned ticket TKT-004: Marketing campaign analysis',
    ticketId: 't4',
    read: false,
    createdAt: new Date(new Date().setHours(new Date().getHours() - 3)).toISOString(),
  },
  {
    id: 'n6',
    userId: 'u7',
    type: 'ticket_assigned',
    title: 'New Ticket Assigned',
    message: 'You have been assigned ticket TKT-005: Database optimization task',
    ticketId: 't5',
    read: false,
    createdAt: new Date(new Date().setHours(new Date().getHours() - 1)).toISOString(),
  },
  {
    id: 'n7',
    userId: 'u7',
    type: 'ticket_assigned',
    title: 'New Ticket Assigned',
    message: 'You have been assigned ticket TKT-006: API integration project',
    ticketId: 't6',
    read: false,
    createdAt: new Date(new Date().setHours(new Date().getHours() - 2)).toISOString(),
  },
];